#!/bin/sh

cd "$(dirname "$(command -v "$0")")" || exit 1

root_dir="$(realpath "$PWD")"

cd "$root_dir" || exit 1

exe/sudo-login || exit 1

eval "$(exe/print-vars 'envs.conf')"

PATH="$(realpath 'php/paths'):$PATH"

if [ "$HOME_DIR" != "$HOME" ] ; then
    mkdir -p "$HOME_DIR"
fi

ins/install-dist
ins/install-xfce
