#!/bin/sh

cd "$(dirname "$(command -v "$0")")" || exit 1

root_dir="$(realpath "$PWD/..")"

cd "$root_dir" || exit 1

sudo_login()
{
    while true ; do
        printf 'Enter password for sudo: '
        stty -echo
        read -r sudo_password
        stty echo
        sudo -k
        echo "$sudo_password" | sudo -p '' -S echo '' > /dev/null 2>&1
        if [ "$?" -eq 0 ] ; then
            echo 'OK'
            break
        else
            exit
        fi
    done
}

sudo_exec()
{
    sudo -k && printf "%s" "$sudo_password" | sudo -p '' -S sh -c "$1" 2>&1
}

start()
{
    sudo_exec 'update-grub'
}

sudo_login

start
