version: 2

jobs:
    build:
        docker:
            - image: cimg/base:stable
              auth:
                  username: $DOCKER_HUB_USERNAME
                  password: $DOCKER_HUB_PASSWORD
        steps:
            - checkout
            - setup_remote_docker
            - run: sudo apt-get update
            - run: sudo apt-get install -y shunit2
            - run: exe/tests/test
            - run: paths/tests/test
