#!/bin/sh

cd "$(dirname "$(command -v "$0")")" || exit 1

root_dir="$(realpath "$PWD/..")"

cd "$root_dir" || exit 1

call_trace="$1"
source="$2"
target="$3"

exe/cmd-sudo "$SUBCHANNEL_EXEC" "$call_trace -> $0" "cp -r -v \"$source\" \"$target\""

exe/cmd "$SUBCHANNEL_TEST" "$call_trace -> $0" "if [ -e \"$target\" ] ; then echo \"Target \\\"$target\\\" was copied successfully.\" ; exit 0 ; else echo \"Target \\\"$target\\\" was not copied.\" ; exit 1 ; fi"
