#!/bin/sh

cd "$(dirname "$(command -v "$0")")" || exit 1

root_dir="$(realpath "$PWD/..")"

cd "$root_dir" || exit 1

call_trace="$1"
path="$2"
dest="$3"
max_tries="$DOWNLOAD_MAX_TRIES"

while [ "$max_tries" -gt 0 ] ; do
    lib/rm "$call_trace -> $0" "$dest"
    exe/cmd "$SUBCHANNEL_EXEC" "$call_trace -> $0" "curl -f -s -L -S \"$path\" -o \"$dest\""
    if [ -e "$dest" ] ; then
        break
    fi
    max_tries="$((max_tries - 1))"
    if [ "$max_tries" -eq 0 ] ; then
        exe/log-error "$SUBCHANNEL_EXEC" "$call_trace -> $0" "$0" "Could not download from \\\"$path\\\". No more attempts left."
    else
        exe/log-error "$SUBCHANNEL_EXEC" "$call_trace -> $0" "$0" "Could not download from \\\"$path\\\". $max_tries attempts left. Trying to download again."
    fi
done

exe/cmd "$SUBCHANNEL_TEST" "$call_trace -> $0" "if [ -f \"$dest\" ] ; then echo \"File \\\"$dest\\\" was downloaded successfully.\" ; exit 0 ; else \"File \\\"$dest\\\" was not downloaded.\" ; exit 1 ; fi"
