#!/bin/sh

cd "$(dirname "$(command -v "$0")")" || exit 1

root_dir="$(realpath "$PWD/../..")"

cd "$root_dir" || exit 1

call_trace="$1"

xfce/bin/xfce4-panel-launcher "$call_trace -> $0" 'sqlitebrowser.desktop' 'DB Browser for SQLite' 'DB Browser for SQLite is a light GUI editor for SQLite databases' 'sqlitebrowser %f' 'sqlitebrowser' 'false'
