#!/bin/sh

cd "$(dirname "$(command -v "$0")")" || exit 1

root_dir="$(realpath "$PWD/../..")"

cd "$root_dir" || exit 1

call_trace="$1"

xfce/bin/xfce4-panel-launcher "$call_trace -> $0" 'steam.desktop' 'Steam' 'Application for managing and playing games on Steam' "sh -c 'STEAM_FRAME_FORCE_CLOSE=1 steam' %U" 'steam' 'false'
