#!/bin/sh

cd "$(dirname "$(command -v "$0")")" || exit 1

root_dir="$(realpath "$PWD/../..")"

cd "$root_dir" || exit 1

call_trace="$1"

xfce/bin/xfce4-panel-launcher "$call_trace -> $0" 'kcachegrind.desktop' 'KCachegrind' 'Visualization of Performance Profiling Data' 'kcachegrind -qwindowtitle %c %u' 'kcachegrind' 'false'
