#!/bin/sh

if [ "$#" -eq 0 ] ; then
    sh -c "$(which -a date | sed -n '2p')"
elif [ "$1" = '+%Y-%m-%d-%H-%M-%S' ] ; then
    echo '2000-01-01-12-00-00'
else
    sh -c "$(which -a date | sed -n '2p') $*"
fi
