#!/bin/sh

cd "$(dirname "$(command -v "$0")")" || exit 1

root_dir="$(realpath "$PWD/../..")"

cd "$root_dir" || exit 1

exe/section "$0"

xfce/lib/xfconf-query-thunar-int "$0" '/last-separator-position' '170'
xfce/lib/xfconf-query-thunar-int "$0" '/last-window-height' '675'
xfce/lib/xfconf-query-thunar-int "$0" '/last-window-width' '630'
