#!/bin/sh

cd "$(dirname "$(command -v "$0")")" || exit 1

root_dir="$(realpath "$PWD/..")"

cd "$root_dir" || exit 1

call_trace="$1"

exe/cmd-sudo "$SUBCHANNEL_EXEC" "$call_trace -> $0" 'apt-get update -q -y'
