#!/bin/sh

cd "$(dirname "$(command -v "$0")")" || exit 1

root_dir="$(realpath "$PWD/..")"

cd "$root_dir" || exit 1

call_trace="$1"
package="$2"

exe/cmd-sudo "$SUBCHANNEL_EXEC" "$call_trace -> $0" "apt-get remove -q -y \"$package\""
