#!/bin/sh

cd "$(dirname "$(command -v "$0")")" || exit 1

root_dir="$(realpath "$PWD/..")"

cd "$root_dir" || exit 1

call_trace="$1"
package="$2"
pkgname="$(echo "$package" | cut -d '=' -f 1)"
max_tries="$DOWNLOAD_MAX_TRIES"

while [ "$max_tries" -gt 0 ] ; do
    exe/cmd-sudo "$SUBCHANNEL_EXEC" "$call_trace -> $0" "apt-get install -q -y \"$package\""
    if [ "$(dpkg -s "$pkgname" 2> /dev/null | grep '^Status')" = 'Status: install ok installed' ] ; then
        break
    fi
    max_tries="$((max_tries - 1))"
    if [ "$max_tries" -eq 0 ] ; then
        exe/log-error "$SUBCHANNEL_EXEC" "$call_trace -> $0" "$0" "Could not install \\\"$pkgname\\\". No more attempts left."
    else
        exe/log-error "$SUBCHANNEL_EXEC" "$call_trace -> $0" "$0" "Could not install \\\"$pkgname\\\". $max_tries attempts left. Trying to install again."
    fi
done

exe/cmd "$SUBCHANNEL_TEST" "$call_trace -> $0" "if [ \"$(dpkg -s "$pkgname" 2> /dev/null | grep '^Status')\" = 'Status: install ok installed' ] ; then echo \"Package \\\"$pkgname\\\" was installed successfully.\" ; exit 0 ; else echo \"Package \\\"$pkgname\\\" was not installed.\" ; exit 1 ; fi"
